## 00. Pytorch Fundamentals

*   List item
*   List item


Resource notebook: https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb

questions: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [29]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cpu


In [30]:
TENSOR = torch.tensor([[[1,2,3,9],
                        [3,6,9,9],
                        [2,4,5,9],
                        [1,2,3,4]],
                       [[1,2,3,9],
                        [3,6,9,9],
                        [2,4,5,9],
                        [1,2,3,4]]
                       ])
TENSOR.ndim

3

# Random Tensors
` start with random numbers -> look at data -> update random -> look at data -> update random`

In [31]:
# create a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6902, 0.5503, 0.3606, 0.4470],
        [0.6482, 0.5507, 0.3927, 0.0346],
        [0.9044, 0.2603, 0.2405, 0.3974]])

In [32]:
random_tensor.ndim

2

In [33]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 244, 244))
random_image_size_tensor

tensor([[[0.2941, 0.3031, 0.8162,  ..., 0.6926, 0.0794, 0.0607],
         [0.7545, 0.8710, 0.2429,  ..., 0.1907, 0.3088, 0.8897],
         [0.4102, 0.9622, 0.7260,  ..., 0.6966, 0.2383, 0.9894],
         ...,
         [0.3185, 0.4818, 0.4425,  ..., 0.9903, 0.5369, 0.8718],
         [0.8533, 0.7966, 0.9268,  ..., 0.8666, 0.4004, 0.4306],
         [0.5920, 0.4921, 0.8430,  ..., 0.6331, 0.7284, 0.5140]],

        [[0.9030, 0.8170, 0.7018,  ..., 0.7624, 0.8685, 0.3985],
         [0.0558, 0.0347, 0.3426,  ..., 0.7908, 0.1966, 0.4063],
         [0.4149, 0.4024, 0.5947,  ..., 0.1116, 0.7724, 0.6263],
         ...,
         [0.9485, 0.6842, 0.0061,  ..., 0.8486, 0.4489, 0.0343],
         [0.2097, 0.2141, 0.2538,  ..., 0.5825, 0.5655, 0.6547],
         [0.9449, 0.5714, 0.8998,  ..., 0.3212, 0.0892, 0.7407]],

        [[0.9531, 0.2697, 0.1437,  ..., 0.9560, 0.4391, 0.7195],
         [0.4852, 0.6993, 0.6143,  ..., 0.2075, 0.0857, 0.1708],
         [0.6681, 0.6368, 0.3089,  ..., 0.6779, 0.1634, 0.

In [34]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([3, 244, 244]))

# Zeros and Ones 
useful for masks

In [35]:
# Create a tensor for all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
zeros* torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
# Ones
ones = torch.ones(1,4,4)
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [38]:
# Ones
ones = torch.ones(4,4,1)
ones

tensor([[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]])

In [39]:
ones.dtype, zeros.dtype

(torch.float32, torch.float32)

# Creating a range of tensors and tensors-like

In [40]:
# 
ranges = torch.arange(start=1,end=500, step =  50)
ranges

tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451])

In [41]:
# Creating tensors like
zeros_like_ranges = torch.zeros_like(input=ranges)
zeros_like_ranges

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatype

In [42]:
# Float 32 tensor is the default
float_32_tensor = torch.tensor([3.1, 6.4, 9.0], 
                               dtype = None,
                               device = None, 
                               requires_grad = False) # whether or not to track gradeints with this tensors operations
float_32_tensor.dtype

torch.float32

In [43]:
# Float 16 tensor is the default
float_16_tensor = torch.tensor([3.1, 6.4, 9.0], 
                               dtype = torch.float16,
                               device = None,
                               requires_grad = False)
float_16_tensor.dtype

torch.float16

In [44]:
float_16_tensor

tensor([3.0996, 6.3984, 9.0000], dtype=torch.float16)

In [45]:
# CPU
cpu = torch.tensor([3.1, 6.4, 9.0], 
                               
                               device = 'cpu',
                               requires_grad = False)
cpu.device

device(type='cpu')

In [46]:
TENSOR.device

device(type='cpu')

In [47]:
# Change dtype
float_half = float_32_tensor.type(torch.float16)
float_half

tensor([3.0996, 6.3984, 9.0000], dtype=torch.float16)

In [48]:
# Change dtype
float_half = float_32_tensor.type(torch.half)
float_half

tensor([3.0996, 6.3984, 9.0000], dtype=torch.float16)

### Getting  Tensors Attributes
1. Tensor not right datatype - to get datatype from a tensor, can use `tensor.type`
2. `tensor.shape` to know the shape
2.   `tensor.device` to know the right device

In [49]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8980, 0.0576, 0.9317, 0.9142],
        [0.3759, 0.5165, 0.7520, 0.3415],
        [0.0549, 0.5911, 0.3147, 0.4374]])

In [50]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.8980, 0.0576, 0.9317, 0.9142],
        [0.3759, 0.5165, 0.7520, 0.3415],
        [0.0549, 0.5911, 0.3147, 0.4374]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [51]:
some_tens = some_tensor.type(torch.half)
some_tens.dtype

torch.float16

In [52]:
some_tens

tensor([[0.8979, 0.0576, 0.9316, 0.9141],
        [0.3760, 0.5166, 0.7520, 0.3416],
        [0.0549, 0.5913, 0.3147, 0.4375]], dtype=torch.float16)

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix  multiplication

In [53]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [54]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [55]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [56]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

# Matrix Manipulation
two types:
1. element-wise multiplication
2. matrix multiplication (dot product)

for more details visit: https://www.mathsisfun.com/algebra/matrix-multiplying.html

Main rules:
1. The **inner dimensions** must match
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` gives `(2,2)`


In [58]:
# element wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [59]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [65]:
test22   = torch.randint(low=0, high=5, size=(2,2))
test22_2 = torch.randint(low=6, high=13, size=(2,2))
print(test22,'\n', test22_2)

tensor([[1, 3],
        [1, 1]]) 
 tensor([[10,  6],
        [ 8,  9]])


In [66]:
torch.matmul(test22, test22_2)

tensor([[34, 33],
        [18, 15]])

In [71]:
# testing dot product
test12 = torch.tensor([5, 1, 4])
test12

tensor([5, 1, 4])

In [72]:
test12.shape

torch.Size([3])

In [82]:
# this wont work
# torch.matmul(test22, test12);

In [80]:
# Outer dimenstions will be the output (3,2)@(3,2) gives (3,3)
torch.matmul(torch.rand(3,2), torch.rand(2,3)).shape

torch.Size([3, 3])

In [83]:
torch.matmul(torch.rand(4,2), torch.rand(2,3)).shape

torch.Size([4, 3])

#### One of the most commn errors in deep learning: shape error
http://matrixmultiplication.xyz/

In [85]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,1],
                         [8,2],
                         [9,3]])

In [87]:
torch.mm(tensor_A, tensor_B) # this results into an error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)