## 00. Pytorch Fundamentals

*   List item
*   List item


Resource notebook: https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb

questions: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cpu


In [2]:
TENSOR = torch.tensor([[[1,2,3,9],
                        [3,6,9,9],
                        [2,4,5,9],
                        [1,2,3,4]],
                       [[1,2,3,9],
                        [3,6,9,9],
                        [2,4,5,9],
                        [1,2,3,4]]
                       ])
TENSOR.ndim

3

# Random Tensors
` start with random numbers -> look at data -> update random -> look at data -> update random`

In [3]:
# create a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0639, 0.6467, 0.4558, 0.3272],
        [0.1606, 0.1188, 0.6239, 0.2368],
        [0.9988, 0.7718, 0.4687, 0.8601]])

In [4]:
random_tensor.ndim

2

In [5]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 244, 244))
random_image_size_tensor

tensor([[[0.4646, 0.0029, 0.9786,  ..., 0.7006, 0.0206, 0.6328],
         [0.6992, 0.1086, 0.3773,  ..., 0.0592, 0.8155, 0.9365],
         [0.2723, 0.5470, 0.9301,  ..., 0.3738, 0.6652, 0.6170],
         ...,
         [0.3874, 0.0771, 0.0621,  ..., 0.6846, 0.5817, 0.6811],
         [0.3518, 0.9911, 0.0362,  ..., 0.3819, 0.2832, 0.9826],
         [0.0078, 0.0059, 0.3994,  ..., 0.2093, 0.8883, 0.6188]],

        [[0.6150, 0.4674, 0.5975,  ..., 0.2129, 0.9226, 0.1852],
         [0.6208, 0.6206, 0.3449,  ..., 0.1432, 0.5768, 0.6172],
         [0.8436, 0.7101, 0.7763,  ..., 0.7742, 0.7733, 0.8994],
         ...,
         [0.9336, 0.4151, 0.8448,  ..., 0.3895, 0.4233, 0.3559],
         [0.6839, 0.6344, 0.3420,  ..., 0.6645, 0.2622, 0.1120],
         [0.3766, 0.1781, 0.1342,  ..., 0.8150, 0.4322, 0.6180]],

        [[0.3096, 0.2852, 0.9105,  ..., 0.0069, 0.3824, 0.7778],
         [0.4910, 0.2235, 0.3913,  ..., 0.4827, 0.4706, 0.8944],
         [0.0285, 0.2022, 0.0770,  ..., 0.5472, 0.9731, 0.

In [6]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([3, 244, 244]))

# Zeros and Ones 
useful for masks

In [7]:
# Create a tensor for all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
zeros* torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
# Ones
ones = torch.ones(1,4,4)
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
# Ones
ones = torch.ones(4,4,1)
ones

tensor([[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]])

In [11]:
ones.dtype, zeros.dtype

(torch.float32, torch.float32)

# Creating a range of tensors and tensors-like

In [12]:
# 
ranges = torch.arange(start=1,end=500, step =  50)
ranges

tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451])

In [13]:
# Creating tensors like
zeros_like_ranges = torch.zeros_like(input=ranges)
zeros_like_ranges

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatype

In [14]:
# Float 32 tensor is the default
float_32_tensor = torch.tensor([3.1, 6.4, 9.0], 
                               dtype = None,
                               device = None, 
                               requires_grad = False) # whether or not to track gradeints with this tensors operations
float_32_tensor.dtype

torch.float32

In [15]:
# Float 16 tensor is the default
float_16_tensor = torch.tensor([3.1, 6.4, 9.0], 
                               dtype = torch.float16,
                               device = None,
                               requires_grad = False)
float_16_tensor.dtype

torch.float16

In [16]:
float_16_tensor

tensor([3.0996, 6.3984, 9.0000], dtype=torch.float16)

In [17]:
# CPU
cpu = torch.tensor([3.1, 6.4, 9.0], 
                               
                               device = 'cpu',
                               requires_grad = False)
cpu.device

device(type='cpu')

In [18]:
TENSOR.device

device(type='cpu')

In [19]:
# Change dtype
float_half = float_32_tensor.type(torch.float16)
float_half

tensor([3.0996, 6.3984, 9.0000], dtype=torch.float16)

In [20]:
# Change dtype
float_half = float_32_tensor.type(torch.half)
float_half

tensor([3.0996, 6.3984, 9.0000], dtype=torch.float16)

### Getting  Tensors Attributes
1. Tensor not right datatype - to get datatype from a tensor, can use `tensor.type`
2. `tensor.shape` to know the shape
2.   `tensor.device` to know the right device

In [21]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6783, 0.1888, 0.4491, 0.6129],
        [0.0459, 0.1594, 0.0318, 0.5720],
        [0.7355, 0.0290, 0.1975, 0.0720]])

In [22]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.6783, 0.1888, 0.4491, 0.6129],
        [0.0459, 0.1594, 0.0318, 0.5720],
        [0.7355, 0.0290, 0.1975, 0.0720]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [23]:
some_tens = some_tensor.type(torch.half)
some_tens.dtype

torch.float16

In [24]:
some_tens

tensor([[0.6782, 0.1887, 0.4492, 0.6128],
        [0.0458, 0.1594, 0.0318, 0.5718],
        [0.7354, 0.0290, 0.1975, 0.0720]], dtype=torch.float16)

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix  multiplication

In [25]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [26]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [27]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [28]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

# Matrix Manipulation
two types:
1. element-wise multiplication
2. matrix multiplication (dot product)

for more details visit: https://www.mathsisfun.com/algebra/matrix-multiplying.html

Main rules:
1. The **inner dimensions** must match
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` gives `(2,2)`


In [29]:
# element wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [30]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [31]:
test22   = torch.randint(low=0, high=5, size=(2,2))
test22_2 = torch.randint(low=6, high=13, size=(2,2))
print(test22,'\n', test22_2)

tensor([[2, 0],
        [2, 0]]) 
 tensor([[ 9, 10],
        [ 7, 10]])


In [32]:
torch.matmul(test22, test22_2)

tensor([[18, 20],
        [18, 20]])

In [33]:
# testing dot product
test12 = torch.tensor([5, 1, 4])
test12

tensor([5, 1, 4])

In [34]:
test12.shape

torch.Size([3])

In [35]:
# this wont work
# torch.matmul(test22, test12);

In [36]:
# Outer dimenstions will be the output (3,2)@(3,2) gives (3,3)
torch.matmul(torch.rand(3,2), torch.rand(2,3)).shape

torch.Size([3, 3])

In [37]:
torch.matmul(torch.rand(4,2), torch.rand(2,3)).shape

torch.Size([4, 3])

#### One of the most commn errors in deep learning: shape error
http://matrixmultiplication.xyz/

In [38]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,1],
                         [8,2],
                         [9,3]])

In [39]:
torch.mm(tensor_A, tensor_B) # this results into an error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### Transpose
in order to overcome shape errors, we *transpose* our tensors


In [40]:
tensor_B.T

tensor([[7, 8, 9],
        [1, 2, 3]])

In [41]:
tensor_B.T.shape

torch.Size([2, 3])

In [42]:
torch.mm(tensor_A, tensor_B.T) # this works

tensor([[ 9, 12, 15],
        [25, 32, 39],
        [41, 52, 63]])