## 00. Pytorch Fundamentals

*   List item
*   List item


Resource notebook: https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb

questions: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [40]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cpu


In [41]:
TENSOR = torch.tensor([[[1,2,3,9],
                        [3,6,9,9],
                        [2,4,5,9],
                        [1,2,3,4]],
                       [[1,2,3,9],
                        [3,6,9,9],
                        [2,4,5,9],
                        [1,2,3,4]]
                       ])
TENSOR.ndim

3

# Random Tensors
` start with random numbers -> look at data -> update random -> look at data -> update random`

In [42]:
# create a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5279, 0.3024, 0.1307, 0.0299],
        [0.5185, 0.3766, 0.0862, 0.7558],
        [0.1886, 0.0427, 0.8822, 0.7031]])

In [43]:
random_tensor.ndim

2

In [44]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 244, 244))
random_image_size_tensor

tensor([[[0.7563, 0.9231, 0.5587,  ..., 0.8262, 0.9433, 0.7607],
         [0.1021, 0.7780, 0.6238,  ..., 0.8845, 0.0529, 0.6929],
         [0.1762, 0.3480, 0.0208,  ..., 0.3436, 0.4252, 0.0618],
         ...,
         [0.9521, 0.2061, 0.8952,  ..., 0.5589, 0.1154, 0.7754],
         [0.8858, 0.5582, 0.4039,  ..., 0.3556, 0.1676, 0.6145],
         [0.0746, 0.0075, 0.3369,  ..., 0.6644, 0.5306, 0.3677]],

        [[0.5787, 0.5428, 0.3017,  ..., 0.0756, 0.1107, 0.8056],
         [0.9180, 0.3913, 0.3087,  ..., 0.5569, 0.8266, 0.8002],
         [0.4360, 0.5531, 0.9249,  ..., 0.1803, 0.3017, 0.3873],
         ...,
         [0.8132, 0.8042, 0.4646,  ..., 0.6180, 0.8451, 0.1382],
         [0.9062, 0.8710, 0.1774,  ..., 0.9790, 0.9371, 0.1152],
         [0.1611, 0.2521, 0.2196,  ..., 0.9555, 0.7106, 0.7671]],

        [[0.3201, 0.2301, 0.8420,  ..., 0.8421, 0.3152, 0.6456],
         [0.2296, 0.8866, 0.9986,  ..., 0.3698, 0.8165, 0.4702],
         [0.8264, 0.3152, 0.6871,  ..., 0.8437, 0.1408, 0.

In [45]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([3, 244, 244]))

# Zeros and Ones 
useful for masks

In [46]:
# Create a tensor for all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [47]:
zeros* torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [48]:
# Ones
ones = torch.ones(1,4,4)
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [49]:
# Ones
ones = torch.ones(4,4,1)
ones

tensor([[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]])

In [50]:
ones.dtype, zeros.dtype

(torch.float32, torch.float32)

# Creating a range of tensors and tensors-like

In [51]:
# 
ranges = torch.arange(start=1,end=500, step =  50)
ranges

tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451])

In [52]:
# Creating tensors like
zeros_like_ranges = torch.zeros_like(input=ranges)
zeros_like_ranges

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatype

In [53]:
# Float 32 tensor is the default
float_32_tensor = torch.tensor([3.1, 6.4, 9.0], 
                               dtype = None,
                               device = None, 
                               requires_grad = False) # whether or not to track gradeints with this tensors operations
float_32_tensor.dtype

torch.float32

In [54]:
# Float 16 tensor is the default
float_16_tensor = torch.tensor([3.1, 6.4, 9.0], 
                               dtype = torch.float16,
                               device = None,
                               requires_grad = False)
float_16_tensor.dtype

torch.float16

In [55]:
float_16_tensor

tensor([3.0996, 6.3984, 9.0000], dtype=torch.float16)

In [56]:
# CPU
cpu = torch.tensor([3.1, 6.4, 9.0], 
                               
                               device = 'cpu',
                               requires_grad = False)
cpu.device

device(type='cpu')

In [57]:
TENSOR.device

device(type='cpu')

In [58]:
# Change dtype
float_half = float_32_tensor.type(torch.float16)
float_half

tensor([3.0996, 6.3984, 9.0000], dtype=torch.float16)

In [59]:
# Change dtype
float_half = float_32_tensor.type(torch.half)
float_half

tensor([3.0996, 6.3984, 9.0000], dtype=torch.float16)

### Getting  Tensors Attributes
1. Tensor not right datatype - to get datatype from a tensor, can use `tensor.type`
2. `tensor.shape` to know the shape
2.   `tensor.device` to know the right device

In [60]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5470, 0.8436, 0.9802, 0.0715],
        [0.8483, 0.8714, 0.2027, 0.7231],
        [0.5353, 0.8395, 0.0241, 0.0335]])

In [61]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.5470, 0.8436, 0.9802, 0.0715],
        [0.8483, 0.8714, 0.2027, 0.7231],
        [0.5353, 0.8395, 0.0241, 0.0335]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [62]:
some_tens = some_tensor.type(torch.half)
some_tens.dtype

torch.float16

In [63]:
some_tens

tensor([[0.5469, 0.8438, 0.9805, 0.0715],
        [0.8481, 0.8716, 0.2026, 0.7231],
        [0.5352, 0.8394, 0.0241, 0.0335]], dtype=torch.float16)

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix  multiplication

In [64]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [65]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [66]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [67]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

# Matrix Manipulation
two types:
1. element-wise multiplication
2. matrix multiplication (dot product)

for more details visit: https://www.mathsisfun.com/algebra/matrix-multiplying.html

Main rules:
1. The **inner dimensions** must match
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` gives `(2,2)`


In [68]:
# element wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [69]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [70]:
test22   = torch.randint(low=0, high=5, size=(2,2))
test22_2 = torch.randint(low=6, high=13, size=(2,2))
print(test22,'\n', test22_2)

tensor([[3, 3],
        [1, 0]]) 
 tensor([[12, 11],
        [ 9, 12]])


In [71]:
torch.matmul(test22, test22_2)

tensor([[63, 69],
        [12, 11]])

In [72]:
# testing dot product
test12 = torch.tensor([5, 1, 4])
test12

tensor([5, 1, 4])

In [73]:
test12.shape

torch.Size([3])

In [74]:
# this wont work
# torch.matmul(test22, test12);

In [75]:
# Outer dimenstions will be the output (3,2)@(3,2) gives (3,3)
torch.matmul(torch.rand(3,2), torch.rand(2,3)).shape

torch.Size([3, 3])

In [76]:
torch.matmul(torch.rand(4,2), torch.rand(2,3)).shape

torch.Size([4, 3])

#### One of the most commn errors in deep learning: shape error
http://matrixmultiplication.xyz/

In [79]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,1],
                         [8,2],
                         [9,3]])

In [78]:
torch.mm(tensor_A, tensor_B) # this results into an error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### Transpose
in order to overcome shape errors, we *transpose* our tensors


In [80]:
tensor_B.T

tensor([[7, 8, 9],
        [1, 2, 3]])

In [81]:
print(tensor_B.T)
tensor_B.T.shape

tensor([[7, 8, 9],
        [1, 2, 3]])


torch.Size([2, 3])

In [82]:
torch.mm(tensor_A, tensor_B.T) # this works

tensor([[ 9, 12, 15],
        [25, 32, 39],
        [41, 52, 63]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [86]:
# create a tensor
x = torch.arange(0,100,10) + 1
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [87]:
# find min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [88]:
# max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [93]:
# average
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [95]:
# sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))