## 00. Pytorch Fundamentals

*   List item
*   List item


Resource notebook: https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb

questions: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [88]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cpu


In [89]:
TENSOR = torch.tensor([[[1,2,3,9],
                        [3,6,9,9],
                        [2,4,5,9],
                        [1,2,3,4]],
                       [[1,2,3,9],
                        [3,6,9,9],
                        [2,4,5,9],
                        [1,2,3,4]]
                       ])
TENSOR.ndim

3

# Random Tensors
` start with random numbers -> look at data -> update random -> look at data -> update random`

In [90]:
# create a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0163, 0.9022, 0.0770, 0.4494],
        [0.8670, 0.2528, 0.4688, 0.8232],
        [0.1825, 0.4031, 0.8273, 0.8052]])

In [91]:
random_tensor.ndim

2

In [92]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 244, 244))
random_image_size_tensor

tensor([[[0.4657, 0.2648, 0.9879,  ..., 0.1943, 0.0953, 0.1166],
         [0.1869, 0.8783, 0.8610,  ..., 0.5851, 0.8779, 0.5024],
         [0.2896, 0.2771, 0.2535,  ..., 0.6231, 0.4145, 0.9096],
         ...,
         [0.9726, 0.3420, 0.4964,  ..., 0.0635, 0.7266, 0.9954],
         [0.4929, 0.0748, 0.2736,  ..., 0.9052, 0.6710, 0.3969],
         [0.3013, 0.3647, 0.9984,  ..., 0.6287, 0.5693, 0.6764]],

        [[0.7959, 0.4452, 0.3128,  ..., 0.4214, 0.9604, 0.6456],
         [0.9167, 0.2868, 0.6074,  ..., 0.1786, 0.5632, 0.6286],
         [0.2890, 0.7193, 0.2263,  ..., 0.2577, 0.9568, 0.6645],
         ...,
         [0.6776, 0.6912, 0.9649,  ..., 0.0558, 0.7742, 0.4429],
         [0.4135, 0.9883, 0.4958,  ..., 0.9234, 0.4425, 0.1688],
         [0.0440, 0.6590, 0.7793,  ..., 0.9350, 0.0994, 0.0625]],

        [[0.8529, 0.9272, 0.8555,  ..., 0.0013, 0.7416, 0.3809],
         [0.2993, 0.9537, 0.8510,  ..., 0.1897, 0.1274, 0.2415],
         [0.0065, 0.9951, 0.7164,  ..., 0.4632, 0.1519, 0.

In [93]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([3, 244, 244]))

# Zeros and Ones 
useful for masks

In [94]:
# Create a tensor for all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [95]:
zeros* torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [96]:
# Ones
ones = torch.ones(1,4,4)
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [97]:
# Ones
ones = torch.ones(4,4,1)
ones

tensor([[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]])

In [98]:
ones.dtype, zeros.dtype

(torch.float32, torch.float32)

# Creating a range of tensors and tensors-like

In [99]:
# 
ranges = torch.arange(start=1,end=500, step =  50)
ranges

tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451])

In [100]:
# Creating tensors like
zeros_like_ranges = torch.zeros_like(input=ranges)
zeros_like_ranges

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatype

In [101]:
# Float 32 tensor is the default
float_32_tensor = torch.tensor([3.1, 6.4, 9.0], 
                               dtype = None,
                               device = None, 
                               requires_grad = False) # whether or not to track gradeints with this tensors operations
float_32_tensor.dtype

torch.float32

In [102]:
# Float 16 tensor is the default
float_16_tensor = torch.tensor([3.1, 6.4, 9.0], 
                               dtype = torch.float16,
                               device = None,
                               requires_grad = False)
float_16_tensor.dtype

torch.float16

In [103]:
float_16_tensor

tensor([3.0996, 6.3984, 9.0000], dtype=torch.float16)

In [104]:
# CPU
cpu = torch.tensor([3.1, 6.4, 9.0], 
                               
                               device = 'cpu',
                               requires_grad = False)
cpu.device

device(type='cpu')

In [105]:
TENSOR.device

device(type='cpu')

In [106]:
# Change dtype
float_half = float_32_tensor.type(torch.float16)
float_half

tensor([3.0996, 6.3984, 9.0000], dtype=torch.float16)

In [107]:
# Change dtype
float_half = float_32_tensor.type(torch.half)
float_half

tensor([3.0996, 6.3984, 9.0000], dtype=torch.float16)

### Getting  Tensors Attributes
1. Tensor not right datatype - to get datatype from a tensor, can use `tensor.type`
2. `tensor.shape` to know the shape
2.   `tensor.device` to know the right device

In [108]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0566, 0.1371, 0.4881, 0.2991],
        [0.8576, 0.3834, 0.5064, 0.8932],
        [0.0886, 0.6405, 0.7128, 0.4967]])

In [109]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.0566, 0.1371, 0.4881, 0.2991],
        [0.8576, 0.3834, 0.5064, 0.8932],
        [0.0886, 0.6405, 0.7128, 0.4967]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [110]:
some_tens = some_tensor.type(torch.half)
some_tens.dtype

torch.float16

In [111]:
some_tens

tensor([[0.0566, 0.1371, 0.4880, 0.2991],
        [0.8574, 0.3833, 0.5063, 0.8931],
        [0.0886, 0.6406, 0.7129, 0.4968]], dtype=torch.float16)

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix  multiplication

In [112]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [113]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [114]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [115]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

# Matrix Manipulation
two types:
1. element-wise multiplication
2. matrix multiplication (dot product)

for more details visit: https://www.mathsisfun.com/algebra/matrix-multiplying.html

Main rules:
1. The **inner dimensions** must match
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` gives `(2,2)`


In [116]:
# element wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [117]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [118]:
test22   = torch.randint(low=0, high=5, size=(2,2))
test22_2 = torch.randint(low=6, high=13, size=(2,2))
print(test22,'\n', test22_2)

tensor([[2, 1],
        [1, 4]]) 
 tensor([[ 9, 10],
        [12,  8]])


In [119]:
torch.matmul(test22, test22_2)

tensor([[30, 28],
        [57, 42]])

In [120]:
# testing dot product
test12 = torch.tensor([5, 1, 4])
test12

tensor([5, 1, 4])

In [121]:
test12.shape

torch.Size([3])

In [122]:
# this wont work
# torch.matmul(test22, test12);

In [123]:
# Outer dimenstions will be the output (3,2)@(3,2) gives (3,3)
torch.matmul(torch.rand(3,2), torch.rand(2,3)).shape

torch.Size([3, 3])

In [124]:
torch.matmul(torch.rand(4,2), torch.rand(2,3)).shape

torch.Size([4, 3])

#### One of the most commn errors in deep learning: shape error
http://matrixmultiplication.xyz/

In [125]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,1],
                         [8,2],
                         [9,3]])

In [126]:
torch.mm(tensor_A, tensor_B) # this results into an error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)