<a href="https://colab.research.google.com/github/habonimana/PyTorch-for-Deep-Learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

*   List item
*   List item


Resource notebook: https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb

questions: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


In [ ]:
TENSOR = torch.tensor([[[1,2,3,9],
                        [3,6,9,9],
                        [2,4,5,9],
                        [1,2,3,4]],
                       [[1,2,3,9],
                        [3,6,9,9],
                        [2,4,5,9],
                        [1,2,3,4]]
                       ])
TENSOR.ndim

3

# Random Tensors
` start with random numbers -> look at data -> update random -> look at data -> update random`

In [ ]:
# create a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5279, 0.3024, 0.1307, 0.0299],
        [0.5185, 0.3766, 0.0862, 0.7558],
        [0.1886, 0.0427, 0.8822, 0.7031]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 244, 244))
random_image_size_tensor

tensor([[[0.7563, 0.9231, 0.5587,  ..., 0.8262, 0.9433, 0.7607],
         [0.1021, 0.7780, 0.6238,  ..., 0.8845, 0.0529, 0.6929],
         [0.1762, 0.3480, 0.0208,  ..., 0.3436, 0.4252, 0.0618],
         ...,
         [0.9521, 0.2061, 0.8952,  ..., 0.5589, 0.1154, 0.7754],
         [0.8858, 0.5582, 0.4039,  ..., 0.3556, 0.1676, 0.6145],
         [0.0746, 0.0075, 0.3369,  ..., 0.6644, 0.5306, 0.3677]],

        [[0.5787, 0.5428, 0.3017,  ..., 0.0756, 0.1107, 0.8056],
         [0.9180, 0.3913, 0.3087,  ..., 0.5569, 0.8266, 0.8002],
         [0.4360, 0.5531, 0.9249,  ..., 0.1803, 0.3017, 0.3873],
         ...,
         [0.8132, 0.8042, 0.4646,  ..., 0.6180, 0.8451, 0.1382],
         [0.9062, 0.8710, 0.1774,  ..., 0.9790, 0.9371, 0.1152],
         [0.1611, 0.2521, 0.2196,  ..., 0.9555, 0.7106, 0.7671]],

        [[0.3201, 0.2301, 0.8420,  ..., 0.8421, 0.3152, 0.6456],
         [0.2296, 0.8866, 0.9986,  ..., 0.3698, 0.8165, 0.4702],
         [0.8264, 0.3152, 0.6871,  ..., 0.8437, 0.1408, 0.

In [ ]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([3, 244, 244]))

# Zeros and Ones
useful for masks

In [ ]:
# Create a tensor for all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros* torch.rand(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Ones
ones = torch.ones(1,4,4)
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
# Ones
ones = torch.ones(4,4,1)
ones

tensor([[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]])

In [ ]:
ones.dtype, zeros.dtype

(torch.float32, torch.float32)

# Creating a range of tensors and tensors-like

In [ ]:
#
ranges = torch.arange(start=1,end=500, step =  50)
ranges

tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451])

In [ ]:
# Creating tensors like
zeros_like_ranges = torch.zeros_like(input=ranges)
zeros_like_ranges

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatype

In [ ]:
# Float 32 tensor is the default
float_32_tensor = torch.tensor([3.1, 6.4, 9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False) # whether or not to track gradeints with this tensors operations
float_32_tensor.dtype

torch.float32

In [ ]:
# Float 16 tensor is the default
float_16_tensor = torch.tensor([3.1, 6.4, 9.0],
                               dtype = torch.float16,
                               device = None,
                               requires_grad = False)
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor

tensor([3.0996, 6.3984, 9.0000], dtype=torch.float16)

In [ ]:
# CPU
cpu = torch.tensor([3.1, 6.4, 9.0],

                               device = 'cpu',
                               requires_grad = False)
cpu.device

device(type='cpu')

In [ ]:
TENSOR.device

device(type='cpu')

In [ ]:
# Change dtype
float_half = float_32_tensor.type(torch.float16)
float_half

tensor([3.0996, 6.3984, 9.0000], dtype=torch.float16)

In [ ]:
# Change dtype
float_half = float_32_tensor.type(torch.half)
float_half

tensor([3.0996, 6.3984, 9.0000], dtype=torch.float16)

### Getting  Tensors Attributes
1. Tensor not right datatype - to get datatype from a tensor, can use `tensor.type`
2. `tensor.shape` to know the shape
2.   `tensor.device` to know the right device

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5470, 0.8436, 0.9802, 0.0715],
        [0.8483, 0.8714, 0.2027, 0.7231],
        [0.5353, 0.8395, 0.0241, 0.0335]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.5470, 0.8436, 0.9802, 0.0715],
        [0.8483, 0.8714, 0.2027, 0.7231],
        [0.5353, 0.8395, 0.0241, 0.0335]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
some_tens = some_tensor.type(torch.half)
some_tens.dtype

torch.float16

In [ ]:
some_tens

tensor([[0.5469, 0.8438, 0.9805, 0.0715],
        [0.8481, 0.8716, 0.2026, 0.7231],
        [0.5352, 0.8394, 0.0241, 0.0335]], dtype=torch.float16)

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix  multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

# Matrix Manipulation
two types:
1. element-wise multiplication
2. matrix multiplication (dot product)

for more details visit: https://www.mathsisfun.com/algebra/matrix-multiplying.html

Main rules:
1. The **inner dimensions** must match
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` gives `(2,2)`


In [ ]:
# element wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
test22   = torch.randint(low=0, high=5, size=(2,2))
test22_2 = torch.randint(low=6, high=13, size=(2,2))
print(test22,'\n', test22_2)

tensor([[3, 3],
        [1, 0]]) 
 tensor([[12, 11],
        [ 9, 12]])


In [ ]:
torch.matmul(test22, test22_2)

tensor([[63, 69],
        [12, 11]])

In [ ]:
# testing dot product
test12 = torch.tensor([5, 1, 4])
test12

tensor([5, 1, 4])

In [ ]:
test12.shape

torch.Size([3])

In [ ]:
# this wont work
# torch.matmul(test22, test12);

In [ ]:
# Outer dimenstions will be the output (3,2)@(3,2) gives (3,3)
torch.matmul(torch.rand(3,2), torch.rand(2,3)).shape

torch.Size([3, 3])

In [ ]:
torch.matmul(torch.rand(4,2), torch.rand(2,3)).shape

torch.Size([4, 3])

#### One of the most commn errors in deep learning: shape error
http://matrixmultiplication.xyz/

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,1],
                         [8,2],
                         [9,3]])

In [ ]:
torch.mm(tensor_A, tensor_B) # this results into an error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### Transpose
in order to overcome shape errors, we *transpose* our tensors


In [ ]:
tensor_B.T

tensor([[7, 8, 9],
        [1, 2, 3]])

In [ ]:
print(tensor_B.T)
tensor_B.T.shape

tensor([[7, 8, 9],
        [1, 2, 3]])


torch.Size([2, 3])

In [ ]:
torch.mm(tensor_A, tensor_B.T) # this works

tensor([[ 9, 12, 15],
        [25, 32, 39],
        [41, 52, 63]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(1,100,10) + 1
x

tensor([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [ ]:
# find min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
# max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
# average
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the in the tensor that has the minimum value with argmin()-> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(2)

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(92)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking -  combine multiple tensors on top of each other (vstack) or side by side (hstack) (v is vertical h is horizontal)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimensions to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
# let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x.dtype

torch.float32

In [ ]:
# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
# change view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x (the share same memory and they technically same things)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensor on top of each other
x_stacked = torch.stack([x, x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x, x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# Squeeze
x_stacked.size(), torch.squeeze(x_stacked, -2).size()

(torch.Size([9, 4]), torch.Size([9, 4]))

In [ ]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

y = torch.squeeze(x, 0)
y.size()



In [ ]:
x.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [ ]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [ ]:
y = torch.squeeze(x, (1, 2, 3))
y.size()

torch.Size([2, 2, 2])

In [ ]:
x = torch.arange(1., 10.)
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.size()

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
print(f"Previous tensor : {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

print(f"New tensor : {x_reshaped.squeeze()}") # this removes one blacket
print(f"New shape : {x_reshaped.squeeze().shape}")

Previous tensor : tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])
New tensor : tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape : torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (vertical or horizontal)
x_squeezed = x_reshaped.squeeze()
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add extra dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f"New target: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
New target: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# add extra dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=1)

print(f"New target: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

New target: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


## Permute - rearranges the dimensions of a target in a specific order



In [ ]:
x_original = torch.rand(size = (224, 224, 3)) #height width and color
print(x_original.shape)

# permute the original tensor to rearrange the axis (or dim) order

x_permuted = x_original.permute(2,0,1) # shift axis 0->1, 1->2, 2->0
print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [ ]:
another_test = torch.rand(size=(5,5,3))
print(another_test.shape)
another_test

torch.Size([5, 5, 3])


tensor([[[0.3474, 0.1166, 0.2591],
         [0.0804, 0.6707, 0.2048],
         [0.6320, 0.9148, 0.5595],
         [0.6056, 0.6369, 0.9347],
         [0.5436, 0.1846, 0.9779]],

        [[0.3759, 0.4521, 0.3060],
         [0.4214, 0.0033, 0.9985],
         [0.5127, 0.5240, 0.6872],
         [0.7123, 0.5613, 0.7903],
         [0.4880, 0.7939, 0.7612]],

        [[0.5200, 0.9190, 0.8586],
         [0.2616, 0.8788, 0.5516],
         [0.8113, 0.0380, 0.2469],
         [0.1021, 0.9174, 0.6076],
         [0.8927, 0.0755, 0.0170]],

        [[0.3754, 0.5652, 0.4497],
         [0.6007, 0.2076, 0.6277],
         [0.6171, 0.2341, 0.0788],
         [0.0579, 0.8323, 0.1707],
         [0.4306, 0.2778, 0.8251]],

        [[0.1453, 0.4257, 0.6474],
         [0.3913, 0.4612, 0.6796],
         [0.3597, 0.8915, 0.0611],
         [0.3607, 0.0262, 0.6734],
         [0.6283, 0.9063, 0.5743]]])

In [ ]:
another_permuted = another_test.permute(2,0,1)
print(another_permuted.shape)
another_permuted

torch.Size([3, 5, 5])


tensor([[[0.3474, 0.0804, 0.6320, 0.6056, 0.5436],
         [0.3759, 0.4214, 0.5127, 0.7123, 0.4880],
         [0.5200, 0.2616, 0.8113, 0.1021, 0.8927],
         [0.3754, 0.6007, 0.6171, 0.0579, 0.4306],
         [0.1453, 0.3913, 0.3597, 0.3607, 0.6283]],

        [[0.1166, 0.6707, 0.9148, 0.6369, 0.1846],
         [0.4521, 0.0033, 0.5240, 0.5613, 0.7939],
         [0.9190, 0.8788, 0.0380, 0.9174, 0.0755],
         [0.5652, 0.2076, 0.2341, 0.8323, 0.2778],
         [0.4257, 0.4612, 0.8915, 0.0262, 0.9063]],

        [[0.2591, 0.2048, 0.5595, 0.9347, 0.9779],
         [0.3060, 0.9985, 0.6872, 0.7903, 0.7612],
         [0.8586, 0.5516, 0.2469, 0.6076, 0.0170],
         [0.4497, 0.6277, 0.0788, 0.1707, 0.8251],
         [0.6474, 0.6796, 0.0611, 0.6734, 0.5743]]])

In [ ]:
another_test[0,0,0] = 10

In [ ]:
another_permuted[0,0,0]

tensor(10.)

### Indexing (selecting data from a tensors)
indexing with pyTorch is similar to indexing with Numpy

In [ ]:
import torch

x = torch.arange(1,10)
print(x.shape, x)
x = x.reshape(1,3,3)
print(x.shape)
x

torch.Size([9]) tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([1, 3, 3])


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0,2,2]

tensor(9)

In [ ]:
# in this example, the last value will always return a column
print(f"first column {x[:,:,0]}")
print(f"Second column {x[:,:,1]}")
print(f"Third column {x[:,:,2]}")

first column tensor([[1, 4, 7]])
Second column tensor([[2, 5, 8]])
Third column tensor([[3, 6, 9]])


In [ ]:
# in this example, the middle value will always return a row
print(f"first row {x[:,0, :]}")
print(f"Second row {x[:,1, :]}")
print(f"Third row {x[:,2, :]}")

first row tensor([[1, 2, 3]])
Second row tensor([[4, 5, 6]])
Third row tensor([[7, 8, 9]])


### PyTorch tensors & Numpy
Numpy is a popular scientific python numerical computing library
PyTorch interacts with it
* Data in NumPy can be made Tensors `torch.from_numpy(ndarray)`
* From PyTorch to Numpy `torch.Tensor.numpy`

In [ ]:
import torch
import numpy as np

In [ ]:
array = np.arange(1., 8.) # default dtype is float64 and thus this will be carried over to tensor
print(array)
tensor = torch.from_numpy(array)
print(tensor)

[1. 2. 3. 4. 5. 6. 7.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [ ]:
# Tensor to Numpy array
tensor = torch.ones(10)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

### Reproducibility (trying to take the random out of random)

In [ ]:
import torch

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(4,3)
random_tensor_B = torch.rand(4,3)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.5681, 0.5221, 0.6899],
        [0.2353, 0.1047, 0.5473],
        [0.1598, 0.2104, 0.5922],
        [0.9750, 0.9588, 0.4303]])
tensor([[0.7634, 0.5006, 0.1384],
        [0.5448, 0.6193, 0.4694],
        [0.8238, 0.5744, 0.3552],
        [0.1127, 0.6183, 0.3941]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]])


In [ ]:
import random
## set the random seed
RANDOM_SEED = 50
torch.manual_seed(RANDOM_SEED)
random_tensor_H = torch.rand(4,3)
random_tensor_H

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442],
        [0.4605, 0.4877, 0.5927],
        [0.9634, 0.1230, 0.4048]])

In [ ]:
# We have to reset the seed every time otherwise tensor E would be different to tensor_H
torch.manual_seed(RANDOM_SEED)
random_tensor_E = torch.rand(4,3)
random_tensor_E

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442],
        [0.4605, 0.4877, 0.5927],
        [0.9634, 0.1230, 0.4048]])

In [ ]:
random_tensor_E == random_tensor_H

tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])

### Running tensors on GPUs (and making faster computations)

In [ ]:
torch.cuda.is_available() # if this returns True, the PyTorch can see and use GPU

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count number of devices
"""
Knowing the number of GPUs PyTorch has access to is
helpful incase you wanted to run a specific process
on one GPU and another process on another
(PyTorch also has features to let you run a process across all GPUs).

"""
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

You can put tensors (and models, we'll see this later) on a specific device by calling to(device) on them. Where device is the target device you'd like the tensor (or model) to go to.

Why do this?

GPUs offer far faster numerical computing than CPUs do and if a GPU isn't available, because of our device agnostic code (see above), it'll run on the CPU.

In [ ]:
# create tensor (default on CPU)
tensor = torch.arange(1,20)
tensor.device

device(type='cpu')

In [ ]:
# You can move tensor to GPU if available
tensor_gpu = tensor.to(device)
tensor_gpu.device

device(type='cuda', index=0)

### Moving tensors back to the CPU
there are several reasons one need to move a tensor back to CPU. One of the reasons is NUMPY. Numpy can't run on GPU

In [ ]:
tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# Copy tensor back to CPU
tensor_back_cpu = tensor_gpu.cpu().numpy()
tensor_back_cpu

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])